POST http://localhost:4100/users
Content-Type: application/json

{
    "f_name": "Daniel",
    "l_name": "Kiama",
    "email": "muriithikiamad1@gmail.com",
    "role":"spec",
    "password": "12345678" 
}


### Admin Details
# {
#     "f_name": "Sheilla",
#     "l_name": "Chomba",
#     "email": "chombasheila980@gmail.com",
#     "role": "admin",
#     "password": "12345678"
# }


### GETTING ALL USERS

GET http://localhost:4100/users
Content-Type: application/json

### GETTING USER BY ID

GET http://localhost:4100/users/bc0690de-aee6-4533-9144-1416cffd7a09
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiYmMwNjkwZGUtYWVlNi00NTMzLTkxNDQtMTQxNmNmZmQ3YTA5IiwiZl9uYW1lIjoiU2hlaWxsYSIsImxfbmFtZSI6IkNob21iYSIsImVtYWlsIjoiY2hvbWJhc2hlaWxhOTgwQGdtYWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsImlzV2VsY29tZWQiOmZhbHNlLCJpYXQiOjE3MTA3NjA5MjUsImV4cCI6MTcxMDc2NDUyNX0.UymVofSnWsbXzjm5F54dhAYiK8WG6Dbl6hRB__8J02Y

###
PUT http://localhost:4100/users/update/bc0690de-aee6-4533-9144-1416cffd7a09
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiYmMwNjkwZGUtYWVlNi00NTMzLTkxNDQtMTQxNmNmZmQ3YTA5IiwiZl9uYW1lIjoiU2hlaWxsYSIsImxfbmFtZSI6IkNob21iYSIsImVtYWlsIjoiY2hvbWJhc2hlaWxhOTgwQGdtYWlsLmNvbSIsInJvbGUiOiJhZG1pbiIsImlzV2VsY29tZWQiOmZhbHNlLCJpYXQiOjE3MTA3NjA5MjUsImV4cCI6MTcxMDc2NDUyNX0.UymVofSnWsbXzjm5F54dhAYiK8WG6Dbl6hRB__8J02Y

{
    "f_name": "Sheilla",
    "l_name": "Chomba",
    "email": "chombasheila980@gmail.com",
    "password": "12345678"
}

###

DELETE http://localhost:4100/users/delete/db15362c-5770-4c2b-8897-cfb733fcec2f
Content-Type: application/json
token: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VyX2lkIjoiZGIxNTM2MmMtNTc3MC00YzJiLTg4OTctY2ZiNzMzZmNlYzJmIiwiZl9uYW1lIjoiSmFuZSIsImxfbmFtZSI6Ik5nZW5lIiwiZW1haWwiOiJqYW5lbmdlbmUxMkBnbWFpbC5jb20iLCJyb2xlIjoidXNlciIsImlzV2VsY29tZWQiOmZhbHNlLCJpYXQiOjE3MTA3NjExMjEsImV4cCI6MTcxMDc2NDcyMX0.y0fZ347xuQiLRK-BEhDhdeoAHsBnTe_Q3lcQR9ob6vg