POST http://localhost:4100/order
Content-Type: application/json

{
    "spec_id": "7f63e5f2-b9ce-4548-999e-273197e6ea69",
    "user_id": "f4077bec-4bf2-4cdb-afed-28b129126450",
    "order_desc": "Digital Markeeting for my business"
}

### GETTING ALL ORDERS

GET http://localhost:4100/order

### GETTING BY ID

GET http://localhost:4100/order/c03fbe04-5d28-4975-b740-f18f91d5bb9f

### GETTING BY ID FOR EACH SPECIALIST

GET http://localhost:4100/order/spec/7f63e5f2-b9ce-4548-999e-273197e6ea69

### GETTING BY ID FOR EACH USER

GET http://localhost:4100/order/user/db15362c-5770-4c2b-8897-cfb733fcec2f

### UPDATING ORDERS
PUT http://localhost:4100/order/update/f9b478e2-e03b-42b9-bc3c-0eef869172ed
Content-Type: application/json

{
    "order_desc": "Trust your business with us",
    "status":"Completed"
}