POST http://localhost:4100/order
Content-Type: application/json

{
    "spec_id": "b02050da-e12b-4871-8644-a0aa177dc936",
    "user_id": "d67829c0-1a5d-4bc8-b349-a728468da710",
    "order_desc": "I love your amazing project I have another one for you"
}

### GETTING ALL ORDERS

GET http://localhost:4100/order

### GETTING BY ID

GET http://localhost:4100/order/c03fbe04-5d28-4975-b740-f18f91d5bb9f

### GETTING BY ID FOR EACH SPECIALIST

GET http://localhost:4100/order/spec/4a5ef199-868a-4c27-b797-c615aef2044f

### GETTING BY ID FOR EACH USER

GET http://localhost:4100/order/user/db15362c-5770-4c2b-8897-cfb733fcec2f

### UPDATING ORDERS
PUT http://localhost:4100/order/update/f9b478e2-e03b-42b9-bc3c-0eef869172ed
Content-Type: application/json

{
    "order_desc": "Trust your business with us",
    "status":"Completed"
}

### UPDATING ORDERS STATUS
PUT http://localhost:4100/order/update/status/dfb900c3-3412-4e79-a3f6-092f896056a5
Content-Type: application/json

{
    "status":"Accepted"
}