POST http://localhost:4100/order
Content-Type: application/json

{
    "spec_id": "7f63e5f2-b9ce-4548-999e-273197e6ea69",
    "user_id": "db15362c-5770-4c2b-8897-cfb733fcec2f",
    "order_desc": "Trust your business with me"
}

### GETTING ALL ORDERS

GET http://localhost:4100/order

### GETTING BY ID

GET http://localhost:4100/order/f9b478e2-e03b-42b9-bc3c-0eef869172ed

### UPDATING ORDERS
PUT http://localhost:4100/order/update/f9b478e2-e03b-42b9-bc3c-0eef869172ed
Content-Type: application/json

{
    "order_desc": "Trust your business with us",
    "status":"Pending"
}